backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads


collections:
  - label: "Promotions"
    name: "Promotions"
    description: "Enter information for the promo banner."
    files:
      - label: "Promotions"
        name: "promotions"
        file: "src/promotions/promo.json"
        widget: "object"
        fields:
          - label: "promoOne"
          name: "promoOne"
          widget: "object"
          fields: 
          - label: "Title" 
            name: "title" 
            widget: "string"
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
        - label: "promoTwo"
          name: "promoTwo"
          widget: "object"
          fields:
          - label: "Title" 
            name: "title" 
            widget: "string"
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
- label: "promoThree"
          name: "promoThree"
          widget: "object"
          fields:
          - label: "Title" 
            name: "title" 
            widget: "string"
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}