backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads


collections:
  - label: "Promotions"
    name: "Promotions"
    description: "Enter promotional information for the promo banner."
    files:
      - label: "Promotions"
        name: "promotions"
        file: "plublic/promotions/promo.json"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Content, name: subtitle, widget: markdown}
          