backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/images/uploads" # Media files will be stored in the repo under images/uploads


collections:
  - label: "Promotions"
    name: "Promotions"
    description: "Enter information for the promo banner."
    files:
      - label: "Promotions"
        name: "promotions"
        file: "src/data/promo.json"
        widget: "object"
        fields:
          - label: "one"
            name: "one"
            widget: "object"
            fields: 
            - {label: Title, name: title, widget: string}
            - {label: Subtitle, name: subtitle, widget: string}
            - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
            - {label: "Body", name: "body", widget: "markdown"}
          - label: "two"
            name: "two"
            widget: "object"
            fields:
            - {label: Title, name: title, widget: string}
            - {label: Subtitle, name: subtitle, widget: string}
            - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
            - {label: "Body", name: "body", widget: "markdown"}
          - label: "three"
            name: "three"
            widget: "object"
            fields:
            - {label: Title, name: title, widget: string}
            - {label: Subtitle, name: subtitle, widget: string}
            - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
            - {label: "Body", name: "body", widget: "markdown"}
  - label: "About"
    name: "About"
    description: "Enter information for the about section."          
    files:
      - label: "About"
        name: "about"
        file: "src/data/about.json"
        widget: "object"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
          - {label: "Content", name: "content", widget: "markdown"}
  - label: "Hostel"
    name: "Hostel"
    description: "Enter information for the hostel section."          
    files:
      - label: "Hostel"
        name: "hostel"
        file: "src/data/hostel.json"
        widget: "object"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
          - {label: "Content", name: "content", widget: "markdown"}
          - {label: Amenities, name: amenities, widget: list}
          - label: "Room Types"
            name: "rooms"
            widget: "object"
            fields:
              - label: "Full House"
                name: "full"
                widget: "object"
                fields: 
                  - {label: Description, name: description, widget: markdown}
                  - {label: Rate, name: rate, widget: number}
                  - {label: "Image", name: "thumbnail", widget: "image", required: false}
              - label: "Private Room"
                name: "private"
                widget: "object"
                fields: 
                  - {label: Description, name: description, widget: markdown}
                  - {label: Rate, name: rate, widget: number}
                  - {label: "Image", name: "thumbnail", widget: "image", required: false}
              - label: "Shared Room"
                name: "shared"
                widget: "object"
                fields: 
                  - {label: Description, name: description, widget: markdown}
                  - {label: Rate, name: rate, widget: number}
                  - {label: "Image", name: "thumbnail", widget: "image", required: false}
  - label: "Freediving"
    name: "Freediving"
    description: "Enter information for the freediving section."          
    files:
      - label: "Freediving"
        name: "freediving"
        file: "src/data/freediving.json"
        widget: "object"
        fields: 
          - label: "Freediving"
            name: "freediving"
            widget: "object"
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
              - {label: "Content", name: "content", widget: "markdown"}
          - label: "Why Freediving"
            name: "why-freediving"
            widget: "object"
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
              - {label: "Content", name: "content", widget: "markdown"}
  - label: "Scuba Diving"
    name: "Scubadiving"
    description: "Enter information for the scuba diving section."          
    files:
      - label: "Scuba Diving"
        name: "scubadiving"
        file: "src/data/scubadiving.json"
        widget: "object"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
          - {label: "Content", name: "content", widget: "markdown"}
  - label: "Cabo Pulmo"
    name: "Cabo Pulmo"
    description: "Enter information for the Cabo Pulmo section."          
    files:
      - label: "Cabo Pulmo"
        name: "cabopulmo"
        file: "src/data/cabopulmo.json"
        widget: "object"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
          - {label: "Content", name: "content", widget: "markdown"}
  - label: "Whale Shark"
    name: "Whale Shark"
    description: "Enter information for the Whale Shark section."          
    files:
      - label: "Whale Shark"
        name: "whaleshark"
        file: "src/data/whaleshark.json"
        widget: "object"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
          - {label: "Content", name: "content", widget: "markdown"}
  



    